### ISSUE TITLE
False Style Injection

### ISSUE THREAD

**Issue by dictions** [chute/chute-display-components#10]
All styles for all components are being injected when you require any single component.

This is because we're using the Webpack style-loader, but also because we're requiring every component in the `index.js` of this package. So, by importing a component like so:

```
import LiveDisplayPaginator from 'chute-display-components'
```

You are automatically injecting the styles for all other components, even if you're only using a paginator. This can be avoided by explicitly importing components like so:

```
import LiveDisplayPaginator from 'chute-display-components/src/paginators/LiveDisplayPaginator'
```

However, I think there is a cleaner way of doing this. Thoughts?

**Comment by petrbela** [comment]
The style loader has an [option](https://github.com/webpack/style-loader#reference-counted-api) to only inject styles if a component is rendered on a page. It does it by counting the number of instances -- typically call `use`/`unuse` in the mount/unmount event.

**Comment by chiefGui** [comment]
I will be checking out what @petrbela suggested.
